### ISSUE TITLE
Adding wait functionality of nightmare

### ISSUE THREAD

**Issue by NimaSoroush** [matteofigus/mirror-mirror#58]
Hi @matteofigus,

I was playing with this and I understood that there is no waiting mechanism as an option to get benefit from nightmare wait() functionality.

My suggestion is to add new session-operations with wait functionality:
e.g.
```
'use strict';
module.exports = (waitParam) => {
  ...
  session = session.wait(waitParam);
  ...
  return session;
};
```

And in options, we would pass wait as a parameter (number(ms) or string(selector)):
e.g. 
```
runner.setup({
  ...
  wait: 4000,
  ...
});
```
What do you think?

**Comment by matteofigus** [comment]
Sounds good!

**Comment by NimaSoroush** [comment]
Cool, will send a PR for this

**Comment by NimaSoroush** [comment]
Hey @matteofigus: Sorry for not following up on this issue. We actually ended up developing something from scratch with chrome headless which meets our needs much better. [link](https://github.com/NimaSoroush/differencify)
I am happy to close this issue
